# Generated by Django 3.0.5 on 2023-02-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('template_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelogic',
            name='group',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
    ]
