# Generated by Django 3.2.20 on 2023-11-18 10:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelogic',
            name='file_validations',
            field=djongo.models.fields.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatelogic',
            name='file',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
