# Generated by Django 3.1.14 on 2023-03-23 08:35

from django.db import migrations, models
import template_logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='file',
            field=models.FileField(null=True, upload_to=template_logic.models.get_upload_path),
        ),
    ]
