# Generated by Django 3.0.5 on 2023-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0002_templatelogic_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
