# Generated by Django 3.1.14 on 2023-04-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('template_logic', '0002_auto_20230323_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='templatelogic',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
