# Generated by Django 3.2.20 on 2023-11-30 19:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0002_auto_20231118_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelogic',
            name='file_name',
            field=models.CharField(max_length=1024, null=True),
        )
    ]
