# Generated by Django 3.2.20 on 2024-02-11 09:07

from django.db import migrations
import djongo


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0003_auto_20231130_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='send_type',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='templatelogic',
            name='validations',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
