# Generated by Django 3.0.5 on 2023-02-06 19:00

from django.db import migrations, models
import template_logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0004_auto_20230206_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='file',
            field=models.FileField(upload_to=template_logic.models.get_upload_path),
        ),
    ]
