# Generated by Django 3.2.20 on 2024-11-23 11:56

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('template_logic', '0004_auto_20240211_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelogic',
            name='file_validations',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
