version: '3.1'
services:
  funeraria:
    container_name: funeraria_backend
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./funeraria:/funeraria
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - funeraria_backend_frontend
      - funeraria_backend_db
networks:
  funeraria_backend_frontend:
    driver: bridge
  funeraria_backend_db:
    driver: bridge