version: '3.1'
services:
  funeraria:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./funeraria:/funeraria
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000