version: '3'
services:
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    container_name: mongodb
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog
  web:
    build: .
    command: /bin/sh "./project_start.sh"
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
      - mailhog