version: '3.1'
name: Funeraria
services:
  web:
    image: api
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh "./project_start.sh"
    ports:
      - "8000:8000"
    env_file:
      - .env
    