# Generated by Django 3.2.20 on 2024-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='page',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
