# Generated by Django 3.0.5 on 2023-02-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_column='phone', max_length=32)),
                ('email', models.EmailField(db_column='email', max_length=32, null=True)),
                ('status', models.CharField(choices=[('1', 'Inactive'), ('2', 'Active'), ('3', 'Pending'), ('4', 'Completed'), ('5', 'Archived')], db_column='status', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.FileField(null=True, upload_to=records.models.get_upload_path)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], db_column='gender', max_length=64)),
                ('marital_status', models.CharField(choices=[('1', 'Single'), ('2', 'Maried'), ('3', 'Divorced'), ('4', 'Widower')], db_column='marital_status', max_length=64, null=True)),
                ('cc', models.CharField(db_column='cc', max_length=16, null=True, unique=True)),
                ('nif', models.CharField(db_column='nif', max_length=16, null=True, unique=True)),
                ('niss', models.CharField(db_column='niss', max_length=16, null=True, unique=True)),
                ('birthday', models.DateField(db_column='birthday', null=True)),
                ('age', models.IntegerField(db_column='age', null=True)),
                ('address', models.CharField(db_column='address', max_length=255, null=True)),
                ('parish', models.CharField(db_column='parish', max_length=255, null=True)),
                ('municipality', models.CharField(db_column='municipality', max_length=255, null=True)),
                ('mother_name', models.CharField(db_column='mother_name', max_length=255, null=True)),
                ('father_name', models.CharField(db_column='father_name', max_length=255, null=True)),
                ('last_mariage_date', models.DateField(db_column='last_mariage_date', null=True)),
                ('spouse_name', models.CharField(db_column='spouse_name', max_length=255, unique=True)),
                ('spouse_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], db_column='spouse_gender', max_length=64)),
                ('spouse_age', models.IntegerField(db_column='spouse_age', null=True)),
                ('naturality_parish', models.CharField(db_column='naturality_parish', max_length=255, null=True)),
                ('naturality_municipality', models.CharField(db_column='naturality_municipality', max_length=255, null=True)),
                ('death_date', models.DateField(db_column='death_date', null=True)),
                ('death_time', models.TimeField(db_column='death_time', null=True)),
                ('death_address', models.CharField(db_column='death_address', max_length=255, null=True)),
                ('death_parish', models.CharField(db_column='death_parish', max_length=255, null=True)),
                ('death_municipality', models.CharField(db_column='death_municipality', max_length=255, null=True)),
                ('cemetery', models.CharField(db_column='cemetery', max_length=255, null=True)),
                ('cemetery_municipality', models.CharField(db_column='cemetery_municipality', max_length=255, null=True)),
                ('grave_number', models.CharField(db_column='grave_number', max_length=16, null=True)),
                ('grave_row', models.CharField(db_column='grave_row', max_length=16, null=True)),
                ('grave_site', models.CharField(db_column='grave_site', max_length=64, null=True)),
                ('death_retired', models.BooleanField(db_column='death_retired', null=True)),
                ('death_left_assets', models.BooleanField(db_column='death_left_assets', null=True)),
                ('death_made_will', models.BooleanField(db_column='death_made_will', null=True)),
                ('death_leaves_hereditary', models.BooleanField(db_column='death_leaves_hereditary', null=True)),
                ('double_head', models.CharField(db_column='double_head', max_length=255, null=True)),
                ('double_head_address', models.CharField(db_column='double_head_address', max_length=255, null=True)),
                ('flowers', models.TextField(db_column='flowers', max_length=1024, null=True)),
                ('dead_location', models.CharField(db_column='dead_location', max_length=128, null=True)),
                ('cause_of_death', models.CharField(db_column='cause_of_death', max_length=128, null=True)),
                ('grave_message', models.CharField(db_column='grave_message', max_length=128, null=True)),
                ('wake_local', models.CharField(db_column='wake_local', max_length=255, null=True)),
                ('wake_date', models.DateField(db_column='wake_date', null=True)),
                ('wake_time', models.TimeField(db_column='wake_time', null=True)),
                ('leaving_mortuary_datetime', models.DateTimeField(db_column='leaving_mortuary_time', null=True)),
                ('funeral_datetime', models.DateTimeField(db_column='funeral_datetime', null=True)),
                ('funeral_local', models.CharField(db_column='funeral_local', max_length=255, null=True)),
                ('family_member_name', models.CharField(db_column='family_member_name', max_length=255, null=True)),
                ('family_member_cc', models.CharField(db_column='family_member_cc', max_length=16, null=True)),
                ('family_member_cc_valid_until', models.DateField(db_column='family_member_cc_valid_until', null=True)),
                ('family_member_kinship', models.CharField(db_column='family_member_kinship', max_length=64, null=True)),
                ('death_declaration_number', models.CharField(db_column='death_declaration_number', max_length=32, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_created_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_group', to='groups.Group')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
