# Generated by Django 3.1.14 on 2023-07-28 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.AddField(
            model_name='record',
            name='family_member_phone',
            field=models.CharField(db_column='family_member_phone', default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(db_column='gender', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='spouse_gender',
            field=models.CharField(blank=True, db_column='spouse_gender', max_length=64, null=True),
        ),
    ]
