# Generated by Django 3.2.20 on 2023-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cc_valid_until',
            field=models.DateField(blank=True, db_column='cc_valid_until', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='ACTIVE', max_length=64, null=True),
        ),
    ]
