# Generated by Django 3.0.5 on 2023-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Archived', 'Archived')], db_column='status', max_length=64, null=True),
        ),
    ]
