# Generated by Django 3.0.5 on 2023-02-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.IntegerField(db_column='age', null=True),
        ),
    ]
