# Generated by Django 3.0.5 on 2023-03-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20230301_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman'), ('Other', 'Other')], db_column='gender', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Maried', 'Maried'), ('Divorced', 'Divorced'), ('Widower', 'Widower')], db_column='marital_status', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='spouse_gender',
            field=models.CharField(choices=[('Male', 'Man'), ('Female', 'Woman'), ('Other', 'Other')], db_column='spouse_gender', max_length=64, null=True),
        ),
    ]
