# Generated by Django 3.2.20 on 2023-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20231119_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mortuary',
            field=models.CharField(blank=True, db_column='mortuary', max_length=255, null=True),
        ),
    ]
