# Generated by Django 3.0.5 on 2023-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20230228_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='spouse_gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], db_column='spouse_gender', max_length=64, null=True),
        ),
    ]
