# Generated by Django 3.1.14 on 2023-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20230728_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='marital_status',
            field=models.CharField(blank=True, db_column='marital_status', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='Active', max_length=64, null=True),
        ),
    ]
