# Generated by Django 3.2.20 on 2023-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_mortuary'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='family_member_email',
            field=models.CharField(blank=True, db_column='family_member_email', max_length=64, null=True),
        ),
    ]
