# Generated by Django 3.1.14 on 2023-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20230728_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=64, null=True),
        ),
    ]
