# Generated by Django 3.0.5 on 2023-03-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funeraria.middleware.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0004_auto_20230301_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(default=funeraria.middleware.current_user.CurrentUserMiddleware.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
