# Generated by Django 3.2.20 on 2023-10-11 07:45

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('template_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', djongo.models.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template_logic.templatelogic')),
            ],
        ),
    ]
