# Generated by Django 3.2.20 on 2024-02-16 18:55

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtemplates',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_template_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordtemplates',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='record_template_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
