# Generated by Django 3.0.5 on 2023-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Inactive'), ('2', 'Active'), ('3', 'Suspended')], default='2', max_length=64),
        ),
    ]
