# Generated by Django 3.1.14 on 2023-06-09 07:49

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230323_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=accounts.models.get_upload_path),
            preserve_default=False,
        ),
    ]
