# Generated by Django 3.1.14 on 2023-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
