# Generated by Django 3.1.14 on 2023-08-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230809_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
