name: Build and Deploy to gcp
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_KEY }}
        
        - name: Configure auth
          run: |
            gcloud auth configure-docker

        - name: get docker tag
          run: |
            echo $# Get the latest tag
            IMAGE_TAGS=$(gcloud container images list-tags ${{ secrets.GCP_GCR }} --limit=1 --sort-by=~timestamp --format='get(tags)')

            # Parse the version number into an array
            IFS='.' read -ra VERSION <<< "$IMAGE_TAGS"

            # Increment the patch version number
            ((VERSION[2]++))

            # Combine the version number back into a string
            NEW_TAG="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"

            # Set the new tag as an environment variable
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
            echo $NEW_TAGIMAGE_TAGS
        - name: docker-compose build
          run: |
            docker-compose build
        # - name: docker build 
        #   run: |
        #     docker build -t ${{ secrets.GCP_GCR }}:$NEW_TAG .
        - name: Docker tag
          run: |
            docker tag backend_funeraria ${{ secrets.GCP_GCR }}:$NEW_TAG

        - name: Docker push
          run: |
            docker push ${{ secrets.GCP_GCR }}:$NEW_TAG
            
        # - name: Deploy to Cloud Run
        #   run: |
        #     gcloud run deploy funeraria-backend --image ${{ secrets.GCP_GCR }}:$NEW_TAG --region us-central1 --platform managed
        