name: Build and Deploy to gcp
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Set up gcloud CLI
          uses: google-github-actions/setup-gcloud@v2
          with:
            version: '>= 363.0.0'
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_KEY }}
            export_default_credentials: true
  
        - name: Login to GCR
          run: echo "${{ secrets.GCP_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io
  
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ secrets.GCP_GCR }}:v10.0.0