name: Build and Deploy to gcp
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_KEY }}
        
        - name: Configure auth
          run: |
            gcloud auth configure-docker

        - name: pwd
          run: |
            pwd
            ls -la
  
        # - name: Build and push
        #   uses: docker/build-push-action@v5
        #   with:
        #     context: .
        #     push: true
        #     tags: ${{ secrets.GCP_GCR }}:v10.0.0 
        #     cache-from: type=gha
        #     cache-to: type=gha,mode=max 